-- Backup generated by set_contract_autoinc.py
-- SHOW CREATE TABLE output
DROP TABLE IF EXISTS `contract`;
CREATE TABLE `contract` (
  `contract_id` int NOT NULL,
  `contract_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `name_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `place_birth_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `date_birth_of_debtor` date DEFAULT NULL,
  `nik_number_of_debtor` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `street_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `subdistrict_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `district_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `city_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `province_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `phone_number_of_debtor` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `business_partners_relationship` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `business_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `bank_account_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `name_of_bank` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `name_of_account_holder` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `virtual_account_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `topup_contract` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `previous_topup_amount` int DEFAULT NULL,
  `loan_amount` int DEFAULT NULL,
  `term` int DEFAULT NULL,
  `flat_rate` decimal(5,2) DEFAULT NULL,
  `notaris_fee` int DEFAULT NULL,
  `net_amount` int DEFAULT NULL,
  `admin_fee` int DEFAULT NULL,
  `mortgage_amount` int NOT NULL,
  `stamp_amount` int DEFAULT NULL,
  `financing_agreement_amount` int DEFAULT NULL,
  `security_agreement_amount` decimal(15,2) DEFAULT NULL,
  `upgrading_land_rights_amount` decimal(15,2) DEFAULT NULL,
  `admin_rate` decimal(5,2) NOT NULL,
  `tlo` int NOT NULL,
  `life_insurance` int NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `created_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `total_amount` decimal(15,2) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`contract_id`),
  KEY `contract_number` (`contract_number`),
  KEY `contract_number_2` (`contract_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data dump
INSERT INTO `contract` (`contract_id`,`contract_number`,`name_of_debtor`,`place_birth_of_debtor`,`date_birth_of_debtor`,`nik_number_of_debtor`,`street_of_debtor`,`subdistrict_of_debtor`,`district_of_debtor`,`city_of_debtor`,`province_of_debtor`,`phone_number_of_debtor`,`business_partners_relationship`,`business_type`,`bank_account_number`,`name_of_bank`,`name_of_account_holder`,`virtual_account_number`,`topup_contract`,`previous_topup_amount`,`loan_amount`,`term`,`flat_rate`,`notaris_fee`,`net_amount`,`admin_fee`,`mortgage_amount`,`stamp_amount`,`financing_agreement_amount`,`security_agreement_amount`,`upgrading_land_rights_amount`,`admin_rate`,`tlo`,`life_insurance`,`created_at`,`created_by`,`total_amount`,`updated_at`) VALUES (0,'CON401','Hasanah','Bandung','1998-06-09','3473846398473948','Sahnian No 1','Cicadas','Lengkong','Bandung','Jawa Barat','089976543452','Suami','Catering','568746899','Mandiri','Jijah','658769','BON401',746590,10000000,24,'2.50',100000,9500000,50000,9000000,10000,20000,'30000.00','40000.00','2.90',0,0,'2026-02-14 20:13:47','admin','100000.00','2026-02-14 20:13:47');
INSERT INTO `contract` (`contract_id`,`contract_number`,`name_of_debtor`,`place_birth_of_debtor`,`date_birth_of_debtor`,`nik_number_of_debtor`,`street_of_debtor`,`subdistrict_of_debtor`,`district_of_debtor`,`city_of_debtor`,`province_of_debtor`,`phone_number_of_debtor`,`business_partners_relationship`,`business_type`,`bank_account_number`,`name_of_bank`,`name_of_account_holder`,`virtual_account_number`,`topup_contract`,`previous_topup_amount`,`loan_amount`,`term`,`flat_rate`,`notaris_fee`,`net_amount`,`admin_fee`,`mortgage_amount`,`stamp_amount`,`financing_agreement_amount`,`security_agreement_amount`,`upgrading_land_rights_amount`,`admin_rate`,`tlo`,`life_insurance`,`created_at`,`created_by`,`total_amount`,`updated_at`) VALUES (1,'CON001','John Doe','Jakarta','1980-04-15','3201234567890123','Jl. Merdeka No.1','Gambir','Central Jakarta','Jakarta','DKI Jakarta','081234567890','ABC Corp.','Retail','1234567890','Bank Mandiri','John Doe','VA1234567890','B001',1000000,50000000,12,'5.00',50000,950000,30000,12250000,10000,89000,'280000.00','400000.00','2.50',100000,100000,'2026-02-03 20:29:48','admin','300000.00','2026-02-03 20:29:48');
INSERT INTO `contract` (`contract_id`,`contract_number`,`name_of_debtor`,`place_birth_of_debtor`,`date_birth_of_debtor`,`nik_number_of_debtor`,`street_of_debtor`,`subdistrict_of_debtor`,`district_of_debtor`,`city_of_debtor`,`province_of_debtor`,`phone_number_of_debtor`,`business_partners_relationship`,`business_type`,`bank_account_number`,`name_of_bank`,`name_of_account_holder`,`virtual_account_number`,`topup_contract`,`previous_topup_amount`,`loan_amount`,`term`,`flat_rate`,`notaris_fee`,`net_amount`,`admin_fee`,`mortgage_amount`,`stamp_amount`,`financing_agreement_amount`,`security_agreement_amount`,`upgrading_land_rights_amount`,`admin_rate`,`tlo`,`life_insurance`,`created_at`,`created_by`,`total_amount`,`updated_at`) VALUES (2,'CON002','Jane Smith','Surabaya','1990-06-20','3209876543212345','Jl. Raya No.10','Darmo','Surabaya','East Java','Jawa Timur','082345678901','XYZ Ltd.','Manufacturing','9876543210','BCA','Jane Smith','VA9876543210','B002',1500000,150000000,24,'4.50',60000,1400000,35000,4000000,10000,15000,'280000.00','20000.00','2.67',150000,125000,'2026-02-03 20:29:48','admin','60000.00','2026-02-03 20:29:48');
INSERT INTO `contract` (`contract_id`,`contract_number`,`name_of_debtor`,`place_birth_of_debtor`,`date_birth_of_debtor`,`nik_number_of_debtor`,`street_of_debtor`,`subdistrict_of_debtor`,`district_of_debtor`,`city_of_debtor`,`province_of_debtor`,`phone_number_of_debtor`,`business_partners_relationship`,`business_type`,`bank_account_number`,`name_of_bank`,`name_of_account_holder`,`virtual_account_number`,`topup_contract`,`previous_topup_amount`,`loan_amount`,`term`,`flat_rate`,`notaris_fee`,`net_amount`,`admin_fee`,`mortgage_amount`,`stamp_amount`,`financing_agreement_amount`,`security_agreement_amount`,`upgrading_land_rights_amount`,`admin_rate`,`tlo`,`life_insurance`,`created_at`,`created_by`,`total_amount`,`updated_at`) VALUES (3,'CON003','Michael Johnson','Bandung','1985-08-12','3201234567890126','Jl. Kebon Jeruk No.5','Cibaduyut','Bandung','West Java','Jawa Barat','081298765432','LMN Corp.','Construction','1122334455','Bank BRI','Michael Johnson','VA1122334455','B003',2000000,200000000,36,'6.00',70000,1900000,40000,6000000,220000,15000,'15000.00','20000.00','8.90',150000,100000,'2026-02-03 20:29:48','admin','3250000.00','2026-02-03 20:29:48');
INSERT INTO `contract` (`contract_id`,`contract_number`,`name_of_debtor`,`place_birth_of_debtor`,`date_birth_of_debtor`,`nik_number_of_debtor`,`street_of_debtor`,`subdistrict_of_debtor`,`district_of_debtor`,`city_of_debtor`,`province_of_debtor`,`phone_number_of_debtor`,`business_partners_relationship`,`business_type`,`bank_account_number`,`name_of_bank`,`name_of_account_holder`,`virtual_account_number`,`topup_contract`,`previous_topup_amount`,`loan_amount`,`term`,`flat_rate`,`notaris_fee`,`net_amount`,`admin_fee`,`mortgage_amount`,`stamp_amount`,`financing_agreement_amount`,`security_agreement_amount`,`upgrading_land_rights_amount`,`admin_rate`,`tlo`,`life_insurance`,`created_at`,`created_by`,`total_amount`,`updated_at`) VALUES (4,'CON201','Jimin','Bandung','2000-06-09','3452676547876546','Sayuran No. 15','Cangkuang','Dayeuhkolot','Bandung','Jawa Barat','089976543213','Saudara Kandung','Restoran','73468374938','BCA','Jimin','365427392837','BON201',1340000,10000000,36,'2.50',100000,9800000,200000,60000000,220000,89000,'15000.00','250000.00','42.00',25000,35000,'2026-02-14 11:28:08','admin','310000.00','2026-02-14 11:28:08');
