-- Backup generated by set_uv_collateral_autoinc.py
-- SHOW CREATE TABLE output
DROP TABLE IF EXISTS `uv_collateral`;
CREATE TABLE `uv_collateral` (
  `uv_collateral_id` int NOT NULL AUTO_INCREMENT,
  `contract_number` varchar(50) DEFAULT NULL,
  `wheeled_vehicle` varchar(50) NOT NULL,
  `vehicle_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `vehicle_brand` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `vehicle_model` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `plate_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `chassis_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `engine_number` varchar(50) DEFAULT NULL,
  `manufactured_year` varchar(50) DEFAULT NULL,
  `vehicle_colour` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `bpkb_number` varchar(50) DEFAULT NULL,
  `name_bpkb_owner` varchar(50) DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `update_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`uv_collateral_id`),
  KEY `fk_uv_collateral` (`contract_number`),
  CONSTRAINT `fk_uv_collateral` FOREIGN KEY (`contract_number`) REFERENCES `contract` (`contract_number`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data dump
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (0,'TEST-COLL-001','-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'admin','2026-02-14 14:42:19','2026-02-14 14:42:19');
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (1,'CON001','-','Mobil',NULL,NULL,NULL,'9876543','2345678','2020','Hijau','983647292','Jennie',NULL,NULL,NULL);
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (2,'CON002','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (3,'CON003','','Motor','MMMMMMM','NNNNNNN','D65464CSD','654646','654646','2023','Hitam','54646954','Annn',NULL,NULL,NULL);
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (13,'CON201','roda dua','Motor','Mitsubishi','Basic','D 1234 QWE','7346892379','83746289','2020','Hitam','56374398','Jimin','','2026-02-14 11:28:42','2026-02-14 11:28:42');
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (14,'CON401','roda dua','Motor','AAAA','BBB','CCCC','334576','846538','2020','HDFDHJI','78345683','JDFHGIO','','2026-02-14 20:33:54','2026-02-14 20:33:54');
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (22,'TEST-20260214-002','-','car',NULL,'Toyota',NULL,NULL,NULL,NULL,NULL,NULL,'Owner Name','admin','2026-02-14 14:37:13','2026-02-14 14:37:13');
INSERT INTO `uv_collateral` (`uv_collateral_id`,`contract_number`,`wheeled_vehicle`,`vehicle_type`,`vehicle_brand`,`vehicle_model`,`plate_number`,`chassis_number`,`engine_number`,`manufactured_year`,`vehicle_colour`,`bpkb_number`,`name_bpkb_owner`,`created_by`,`created_at`,`update_at`) VALUES (24,'TEST-UV-COLL-001','-',NULL,NULL,NULL,NULL,NULL,'ENG12345','2020',NULL,'BPKB98765','Pemilik Test','admin','2026-02-14 15:06:12','2026-02-14 15:06:12');
