# Generated by Django 4.2.28 on 2026-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone_number_branch',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
