#!/usr/bin/env python3
import pymysql, time, os, sys

TS = time.strftime('%Y%m%d_%H%M%S')
OUTDIR = os.path.join(os.path.dirname(__file__), 'db_backups')
os.makedirs(OUTDIR, exist_ok=True)
OUTPATH = os.path.join(OUTDIR, f'contract_backup_{TS}.sql')

print('Connecting to MySQL...')
try:
    conn = pymysql.connect(host='127.0.0.1', user='root', password='', db='lolc_operasional', port=3306, charset='utf8mb4')
    cur = conn.cursor()
except Exception as e:
    print('Failed to connect:', e)
    sys.exit(2)

try:
    cur.execute('SHOW CREATE TABLE contract')
    row = cur.fetchone()
    if not row:
        print('No contract table found')
        sys.exit(3)
    create_sql = row[1]

    print('Writing backup to', OUTPATH)
    with open(OUTPATH, 'w', encoding='utf-8') as f:
        f.write('-- Backup generated by set_contract_autoinc.py\n')
        f.write('-- SHOW CREATE TABLE output\n')
        f.write('DROP TABLE IF EXISTS `contract`;\n')
        f.write(create_sql + ';\n\n')

        # dump rows as INSERTs
        cur.execute('SELECT * FROM contract')
        rows = cur.fetchall()
        cols = [d[0] for d in cur.description]
        if rows:
            f.write('-- Data dump\n')
            for r in rows:
                vals = []
                for v in r:
                    if v is None:
                        vals.append('NULL')
                    elif isinstance(v, (int, float)):
                        vals.append(str(v))
                    else:
                        s = str(v)
                        esc = pymysql.converters.escape_string(s)
                        vals.append("'" + esc + "'")
                f.write('INSERT INTO `contract` (`' + '`,`'.join(cols) + '`) VALUES (' + ','.join(vals) + ');\n')

    print('Backup written.')

    print('Altering contract.contract_id to AUTO_INCREMENT...')
    cur.execute('ALTER TABLE contract MODIFY COLUMN contract_id INT NOT NULL AUTO_INCREMENT')
    conn.commit()
    print('ALTER TABLE executed successfully.')
    print('New CREATE TABLE:')
    cur.execute('SHOW CREATE TABLE contract')
    print(cur.fetchone()[1])

except Exception as e:
    print('ERROR', e)
    try:
        conn.rollback()
    except Exception:
        pass
    sys.exit(1)
finally:
    try:
        cur.close()
        conn.close()
    except Exception:
        pass

print('Done.')
