# Generated by Django 4.2.28 on 2026-02-22 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_add_unique_uv_collateral_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('file_type', models.CharField(choices=[('bl', 'BL'), ('uv', 'UV')], max_length=10)),
                ('file_identifier', models.CharField(help_text='ID or path of the downloaded object', max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('stream', 'stream'), ('signed_url', 'signed_url')], default='stream', max_length=20)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'db_table': 'download_log',
            },
        ),
    ]
