# Generated by Django 4.2.28 on 2026-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_downloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, help_text='creator user id (CSA)', null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('download_grants', models.IntegerField(default=1)),
                ('edit_grants', models.IntegerField(default=1)),
                ('download_consumed', models.IntegerField(default=0)),
                ('edit_consumed', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agreement_access',
            },
        ),
    ]
