"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read secret and debug flags from environment for production safety.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-xt!h9_29sn0&sdn%p+y1yf&ml=n(llwtv0-q%tc!6s@=7dc-u(')

# SECURITY WARNING: don't run with debug turned on in production!
# Use `DJANGO_DEBUG=False` in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Restrict hosts in production via `DJANGO_ALLOWED_HOSTS="example.com,api.example.com"`.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# CORS Configuration
# In production, set `CORS_ALLOWED_ORIGINS` to a comma-separated list in env.
env_cors = os.environ.get('CORS_ALLOWED_ORIGINS')
if env_cors:
    CORS_ALLOWED_ORIGINS = [u.strip() for u in env_cors.split(',') if u.strip()]
else:
    # sensible defaults for local development
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3000',
    ]

# Only allow credentials from CORS in debug/dev by default. In production,
# explicitly set `CORS_ALLOW_CREDENTIALS=True` if required for your frontend.
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', str(DEBUG)).lower() in ('1', 'true', 'yes')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myproject',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rolepermissions',
    'rest_framework',
    'rest_framework_simplejwt',
    'myproject.bl_agreement',
    'myproject.uv_agreement',
    'myproject.master_data',
]

# Note: 'rolepermissions' intentionally not added to INSTALLED_APPS here
# to avoid import-time failures for some package versions. If you have
# a working installation of rolepermissions, you can add it back to
# INSTALLED_APPS.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'myproject.models.RawSQLAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'myproject.models.RawSQLJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Ensure CORS allows Authorization header from frontend
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'Authorization',
]

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Role Permissions Configuration
ROLE_PERMISSIONS = {
    'AdminRole': {
        'permissions': [
            'can_view_dashboard',
            'can_manage_users',
        ]
    },
    'UserRole': {
        'permissions': [
            'can_view_dashboard',
        ]
    },
}

# Configure roles
ROLEPERMISSIONS = {
    'module': 'myproject.models',
    'use_cache': True,
}

# Use custom user model that maps to existing `auth_user` table
AUTH_USER_MODEL = 'myproject.CustomUser'


# Database
# Uses MySQL via pymysql (localhost)
# Environment variables used:
# MYSQL_NAME (default: lolc_operasional)
# MYSQL_USER (default: root)
# MYSQL_PASSWORD (default: empty)
# MYSQL_HOST (default: 127.0.0.1)
# MYSQL_PORT (default: 3306)

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_NAME', 'lolc_agreement'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
        'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
        'OPTIONS': {
            # Ensure DB session timezone is UTC to keep DB storage consistent.
            # Also keep strict SQL mode.
            # Set session timezone to UTC. Keep sql_mode setting removed from here
            # to avoid multi-statement init_command issues with certain DB drivers.
            'init_command': "SET time_zone = '+00:00'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

# Use Indonesia Western Time (WIB) = UTC+07:00 for application local timezone
TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Optional: path to LibreOffice `soffice` executable. If set, the PDF view
# will use this exact path when converting DOCX->PDF. If left as None,
# the view will attempt to call `soffice` from PATH and fallback to
# HTML->PDF conversion (WeasyPrint) if unavailable.
# Default: try sensible defaults depending on platform. You can override
# by setting the environment variable `SOFFICE_PATH` to an absolute path
# (e.g. on Windows: "C:\\Program Files\\LibreOffice\\program\\soffice.exe").
SOFFICE_PATH = os.environ.get('SOFFICE_PATH') or (r"C:\Program Files\LibreOffice\program\soffice.exe" if os.name == 'nt' else 'soffice')

import logging.handlers

# Centralized logging configuration including rotating file handler for
# document generation audit log. This ensures `logs/document_generation.log`
# does not grow without bounds.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
        'document_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'INFO',
            'formatter': 'detailed',
            'filename': os.path.join(BASE_DIR, 'logs', 'document_generation.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Application logger used by views and other modules
        'myproject': {
            'handlers': ['console', 'document_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    # Optionally configure root logger so other modules also write to file
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    }
}

# Production-oriented security settings (defaults read from environment)
# These should be explicitly configured in production. Defaults favor local
# development when DEBUG=True.
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', str(not DEBUG)).lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(not DEBUG)).lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', str(not DEBUG)).lower() in ('1', 'true', 'yes')

# HTTP Strict Transport Security
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', str(not DEBUG)).lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')

# Browser security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')

# If running behind a proxy that sets X-Forwarded-Proto, enable this.
if os.environ.get('SECURE_PROXY_SSL_HEADER', 'False').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_PROXY_SSL_HEADER = None
